from flask import Blueprint, jsonify, request
import jwt
import pandas as pd
from datetime import datetime
from calendar import month_name

from sqlalchemy import func, case, inspect
from sqlalchemy.dialects.postgresql import insert

from config import Config
from app import db
from app.models.user_models import Notification, NotificationAlertSKU
from app.utils.token_utils import get_effective_user_id_from_token
from app.utils.live_bi_utils import (
    generate_inventory_alerts_for_all_skus,
    compute_inventory_coverage_ratio,
)

notification_bp = Blueprint("notification_bp", __name__)
SECRET_KEY = Config.SECRET_KEY


def normalize_sku(value):
    if value is None:
        return ""
    return " ".join(str(value).strip().split()).upper()


def table_exists(engine, table_name: str) -> bool:
    try:
        return inspect(engine).has_table(table_name)
    except Exception as e:
        print(f"[WARN] table_exists failed for {table_name}: {e}")
        return False


def load_current_inventory_coverage_df(user_id: int, country: str, month: str = None, year: int = None):
    """
    Load saved current inventory table generated by /current_inventory.

    Expected table name:
      currentinventory_{user_id}_{country}_{month_lower}{year}_table

    Example:
      currentinventory_2_uk_may2026_table
    """
    now = datetime.now()

    if month:
        month_lower = month.strip().lower()
    else:
        month_lower = month_name[now.month].lower()

    if year:
        year_value = int(year)
    else:
        year_value = now.year

    table_name = f"currentinventory_{user_id}_{country}_{month_lower}{year_value}_table"

    if not table_exists(db.engine, table_name):
        return pd.DataFrame(), table_name

    try:
        df = pd.read_sql_table(table_name, db.engine)

        # Remove total row
        if "Product Name" in df.columns:
            df = df[df["Product Name"].astype(str).str.lower() != "total"].copy()

        return df, table_name

    except Exception as e:
        print(f"[ERROR] failed loading current inventory table {table_name}: {e}")
        return pd.DataFrame(), table_name


def build_coverage_map_from_df(coverage_df: pd.DataFrame):
    """Build the SKU inventory context used by notifications and email alerts."""
    coverage_map = {}

    if coverage_df is None or coverage_df.empty:
        return coverage_map

    def first_value(row, names, default=None):
        for name in names:
            if name in row.index:
                value = row.get(name)
                if value is not None and not pd.isna(value):
                    return value
        return default

    def number(row, names, default=0.0):
        value = first_value(row, names, default)
        try:
            return float(pd.to_numeric(value, errors="coerce"))
        except Exception:
            return float(default)

    sku_column = "SKU" if "SKU" in coverage_df.columns else "sku"

    if sku_column not in coverage_df.columns:
        return coverage_map

    for _, row in coverage_df.iterrows():
        sku = row.get(sku_column)
        if sku is None or pd.isna(sku):
            continue

        sku_key = normalize_sku(sku)
        if not sku_key or sku_key == "TOTAL":
            continue

        product_name = first_value(
            row,
            ["Product Name", "product_name"],
            sku_key,
        )

        current_inventory = number(
            row,
            ["total_stock", "Total Stock", "Inventory at the end of the month"],
            0,
        )
        in_transit = number(
            row,
            ["total_transit", "Total Transit", "In Transit Units"],
            0,
        )
        inbound = number(
            row,
            ["inbound_quantity", "Inbound Quantity", "Inventory Inwarded"],
            0,
        )
        sales_last_30_days = number(
            row,
            ["Sales Last 30 Days", "sales_last_30_days", "Unit Sales in Last 30 Days"],
            0,
        )

        current_coverage = number(
            row,
            [
                "Coverage Ratio (In Months)",
                "Coverage Ratio (Current Inventory)",
                "inventory_coverage_ratio",
            ],
            0,
        )
        future_coverage = number(
            row,
            [
                "Coverage Ratio (Current + Intransit)",
                "Coverage Ratio (Current + In Transit)",
                "coverage_ratio_current_intransit",
            ],
            0,
        )

        if not future_coverage and sales_last_30_days > 0:
            future_coverage = (current_inventory + in_transit) / sales_last_30_days

        coverage_map[sku_key] = {
            "inventory_coverage_ratio": round(current_coverage, 2),
            "future_coverage_ratio": round(future_coverage, 2),
            "current_inventory": round(current_inventory, 2),
            "in_transit": round(in_transit, 2),
            "inbound": round(inbound, 2),
            "sales_last_30_days": round(sales_last_30_days, 2),
            "future_stock": round(current_inventory + in_transit, 2),
            "product_name": str(product_name).strip() if product_name else sku_key,
        }

    return coverage_map


def save_notification_to_db(user_id, country, success, message, data, full_response):
    existing = Notification.query.filter_by(
        user_id=user_id,
        country=country
    ).first()

    if existing:
        existing.success = success
        existing.message = message
        existing.data = data
        existing.full_response = full_response
    else:
        db.session.add(
            Notification(
                user_id=user_id,
                country=country,
                success=success,
                message=message,
                data=data,
                full_response=full_response
            )
        )


def upsert_high_alert_sku_atomic(
    user_id,
    country,
    sku,
    product_name,
    alert,
    alert_type,
    current_dt
):
    current_date = current_dt.date()
    current_day_name = current_dt.strftime("%A")

    stmt = insert(NotificationAlertSKU).values(
        user_id=user_id,
        country=country,
        sku=sku,
        product_name=product_name,
        alert=alert,
        alert_type=alert_type,
        first_alert_time=current_dt,
        first_alert_date=current_date,
        first_alert_day_name=current_day_name,
        last_alert_time=current_dt,
        last_alert_date=current_date,
        last_alert_day_name=current_day_name,
        days_since_first_alert=0,
        is_active=True,
    )

    stmt = stmt.on_conflict_do_update(
        constraint="uq_notification_alert_user_country_sku",
        set_={
            "product_name": stmt.excluded.product_name,
            "alert": stmt.excluded.alert,
            "alert_type": stmt.excluded.alert_type,
            "last_alert_time": stmt.excluded.last_alert_time,
            "last_alert_date": stmt.excluded.last_alert_date,
            "last_alert_day_name": stmt.excluded.last_alert_day_name,
            "is_active": True,

            # Preserve first alert fields once they exist
            "first_alert_time": case(
                (
                    NotificationAlertSKU.first_alert_time.is_(None),
                    stmt.excluded.first_alert_time
                ),
                else_=NotificationAlertSKU.first_alert_time
            ),
            "first_alert_date": case(
                (
                    NotificationAlertSKU.first_alert_date.is_(None),
                    stmt.excluded.first_alert_date
                ),
                else_=NotificationAlertSKU.first_alert_date
            ),
            "first_alert_day_name": case(
                (
                    NotificationAlertSKU.first_alert_day_name.is_(None),
                    stmt.excluded.first_alert_day_name
                ),
                else_=NotificationAlertSKU.first_alert_day_name
            ),
            "days_since_first_alert": case(
                (
                    NotificationAlertSKU.first_alert_date.is_(None),
                    0
                ),
                else_=func.cast(
                    stmt.excluded.last_alert_date - NotificationAlertSKU.first_alert_date,
                    db.Integer
                )
            ),
        }
    ).returning(
        NotificationAlertSKU.id,
        NotificationAlertSKU.user_id,
        NotificationAlertSKU.country,
        NotificationAlertSKU.sku,
        NotificationAlertSKU.product_name,
        NotificationAlertSKU.alert,
        NotificationAlertSKU.alert_type,
        NotificationAlertSKU.first_alert_time,
        NotificationAlertSKU.first_alert_date,
        NotificationAlertSKU.first_alert_day_name,
        NotificationAlertSKU.last_alert_time,
        NotificationAlertSKU.last_alert_date,
        NotificationAlertSKU.last_alert_day_name,
        NotificationAlertSKU.days_since_first_alert,
        NotificationAlertSKU.is_active,
    )

    row = db.session.execute(stmt).mappings().first()
    return dict(row)


@notification_bp.route("/notification", methods=["GET", "POST"])
def notification():
    try:
        auth_header = request.headers.get("Authorization")
        if not auth_header or not auth_header.startswith("Bearer "):
            return jsonify({
                "success": False,
                "error": "Authorization token is missing or invalid"
            }), 401

        token = auth_header.split(" ")[1]

        try:
            payload, effective_user_id, member_id = get_effective_user_id_from_token(token)
            user_id = payload["user_id"]
        except jwt.ExpiredSignatureError:
            return jsonify({
                "success": False,
                "error": "Token has expired"
            }), 401
        except jwt.InvalidTokenError:
            return jsonify({
                "success": False,
                "error": "Invalid token"
            }), 401

        request_data = request.get_json(silent=True) or {}

        country = (
            request_data.get("country")
            or request.args.get("country")
            or request.form.get("country")
            or "uk"
        ).strip().lower()

        month = (
            request_data.get("month")
            or request.args.get("month")
            or request.form.get("month")
            or None
        )

        year = (
            request_data.get("year")
            or request.args.get("year")
            or request.form.get("year")
            or None
        )

        if year:
            year = int(year)

        if country not in ["uk", "us", "global"]:
            return jsonify({
                "success": False,
                "error": "Country must be uk, us, or global"
            }), 400

        current_dt = datetime.now()

        # ------------------------------------------------------------
        # 1. Load coverage source.
        # Prefer saved current inventory table because it matches UI.
        # ------------------------------------------------------------
        coverage_df, current_inventory_table_name = load_current_inventory_coverage_df(
            user_id=user_id,
            country=country,
            month=month,
            year=year
        )

        using_current_inventory_table = not coverage_df.empty

        if using_current_inventory_table:
            alerts = generate_inventory_alerts_for_all_skus(
                user_id=user_id,
                country=country,
                coverage_df=coverage_df
            )
        else:
            # Fallback only if current inventory table does not exist
            alerts = generate_inventory_alerts_for_all_skus(user_id, country)
            coverage_df = compute_inventory_coverage_ratio(user_id, country)

        coverage_map = build_coverage_map_from_df(coverage_df)

        

        final_data = {}
        high_alert_seen_skus = set()

        # ------------------------------------------------------------
        # 2. Loop alerts.
        # Store ONLY exact High alert rows in notification_alert_sku.
        # ------------------------------------------------------------
        for raw_sku, alert_info in (alerts or {}).items():
            sku = normalize_sku(raw_sku)
            sku_data = coverage_map.get(sku, {})

            raw_product_name = sku_data.get("product_name")
            if (
                raw_product_name is None
                or pd.isna(raw_product_name)
                or str(raw_product_name).strip() == ""
            ):
                product_name = sku
            else:
                product_name = str(raw_product_name).strip()

            alert_value = (alert_info or {}).get("alert")
            alert_type = (alert_info or {}).get("alert_type")
            inventory_coverage_ratio = sku_data.get("inventory_coverage_ratio")

            

            item_payload = {
                "sku": sku,
                "product_name": product_name,
                "inventory_coverage_ratio": inventory_coverage_ratio,
                "future_coverage_ratio": sku_data.get("future_coverage_ratio"),
                "current_inventory": sku_data.get("current_inventory", 0),
                "in_transit": sku_data.get("in_transit", 0),
                "inbound": sku_data.get("inbound", 0),
                "sales_last_30_days": sku_data.get("sales_last_30_days", 0),
                "future_stock": sku_data.get("future_stock", 0),
                "alert": alert_value,
                "alert_type": alert_type,
            }

            is_high_alert = str(alert_value or "").strip().lower() == "high alert"

            if is_high_alert:
                high_alert_seen_skus.add(sku)

                row = upsert_high_alert_sku_atomic(
                    user_id=user_id,
                    country=country,
                    sku=sku,
                    product_name=product_name,
                    alert=alert_value,
                    alert_type=alert_type,
                    current_dt=current_dt
                )

                item_payload["first_alert_time"] = (
                    row["first_alert_time"].isoformat()
                    if row["first_alert_time"] else None
                )
                item_payload["first_alert_date"] = (
                    str(row["first_alert_date"])
                    if row["first_alert_date"] else None
                )
                item_payload["first_alert_day_name"] = row["first_alert_day_name"]
                item_payload["last_alert_time"] = (
                    row["last_alert_time"].isoformat()
                    if row["last_alert_time"] else None
                )
                item_payload["last_alert_date"] = (
                    str(row["last_alert_date"])
                    if row["last_alert_date"] else None
                )
                item_payload["last_alert_day_name"] = row["last_alert_day_name"]
                item_payload["days_since_first_alert"] = row["days_since_first_alert"]
                item_payload["is_active"] = row["is_active"]

            final_data[product_name] = item_payload


        # ------------------------------------------------------------
        # 3. Mark old high-alert rows inactive if no longer high alert.
        # ------------------------------------------------------------
        if high_alert_seen_skus:
            deactivate_stmt = (
                NotificationAlertSKU.__table__.update()
                .where(NotificationAlertSKU.user_id == user_id)
                .where(NotificationAlertSKU.country == country)
                .where(NotificationAlertSKU.is_active.is_(True))
                .where(NotificationAlertSKU.sku.not_in(list(high_alert_seen_skus)))
                .values(is_active=False)
            )
        else:
            deactivate_stmt = (
                NotificationAlertSKU.__table__.update()
                .where(NotificationAlertSKU.user_id == user_id)
                .where(NotificationAlertSKU.country == country)
                .where(NotificationAlertSKU.is_active.is_(True))
                .values(is_active=False)
            )

        db.session.execute(deactivate_stmt)

        response_payload = {
            "success": True,
            "message": "Notifications fetched successfully",
            "user_id": user_id,
            "country": country,
            "month": month,
            "year": year,
            "source": (
                "current_inventory_table"
                if using_current_inventory_table
                else "compute_inventory_coverage_ratio_fallback"
            ),
            "current_inventory_table": current_inventory_table_name,
            "high_alert_stored_count": len(high_alert_seen_skus),
            "data": final_data
        }

        save_notification_to_db(
            user_id=user_id,
            country=country,
            success=True,
            message="Notifications fetched successfully",
            data=final_data,
            full_response=response_payload
        )

        db.session.commit()

        return jsonify(response_payload), 200

    except Exception as e:
        db.session.rollback()
        print(f"[ERROR] /notification failed: {e}")
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500
    